### ISSUE TITLE
ECRANE milestone

### ISSUE THREAD

**Issue by creeper00** [creeper00/Upenl_newb#218]
<a href="https://github.com/yuyupopo"><img src="https://avatars.githubusercontent.com/u/9143939?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [yuyupopo](https://github.com/yuyupopo)**
_Friday Feb 07, 2020 at 07:52 GMT_
_Originally opened as https://github.com/snuspl/crane/issues/48_

----

> 여러 Job이 최소한의 gpu로 돌고 있다가, 남는 자원이 생기면 random하게 job에게 assign. 각 job은 무조건 승락

- [ ] Implement component tests
- [ ] Add real example.

> 각 job이 거절 할 수 있음 (lease 구현)

depends on #36 
- [ ] implement component test
- [ ] Add real example

>   job 에 priority 줘서 random 보다는 smart하게 offer

- [ ] implement component test
- [ ] add real example
