### ISSUE TITLE
Default app master milestones

### ISSUE THREAD

**Issue by creeper00** [creeper00/Upenl_newb#304]
<a href="https://github.com/KRKimDongWoo"><img src="https://avatars.githubusercontent.com/u/20403194?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [KRKimDongWoo](https://github.com/KRKimDongWoo)**
_Wednesday Feb 19, 2020 at 14:03 GMT_
_Originally opened as https://github.com/snuspl/crane/issues/134_

----

- [x] Cargo run from the app-matser container
- [x] SSH connection between app-master and Cargo
- [x] Run simple mpirun example
- [x] Mount files from the local file system
- [x] ~~Run mounted script automatically (Unnecessary)~~
- [x] Add mount option to cli
- [x] Sends file to cargo containers
- [x] Auto-generated SSH key to cargo containers
- [x] Supports user defined config file of app master
- [x] Supports user defined config file of cargo
- [ ] Lint docstrings, etc.

**Comment by creeper00** [comment]
<a href="https://github.com/yuyupopo"><img src="https://avatars.githubusercontent.com/u/9143939?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yuyupopo](https://github.com/yuyupopo)**
_Wednesday Feb 19, 2020 at 23:16 GMT_

----

Nice summary!

In my opinion, 

We use glusterfs, and each container has default mount directory.
Therefore items like

> Mount files from the local file system

> Sends file to cargo containers

Can be easily done.

**Comment by creeper00** [comment]
<a href="https://github.com/yuyupopo"><img src="https://avatars.githubusercontent.com/u/9143939?v=4" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [yuyupopo](https://github.com/yuyupopo)**
_Saturday Mar 07, 2020 at 14:26 GMT_

----

Are all todos resolved?
